# Generated by Django 5.0.1 on 2024-03-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('USER', 'USER'), ('USER.CREATE.USER', 'USER.CREATE.USER'), ('USER.CREATE.SUPER_ADMIN', 'USER.CREATE.SUPER_ADMIN'), ('USER.CREATE.ADMIN', 'USER.CREATE.ADMIN')], max_length=120, null=True)),
            ],
        ),
    ]
