PERMISSION_CHOICES = [
    ("USER", "USER"),
    ("USER.CREATE.USER", "USER.CREATE.USER"),
    ("USER.CREATE.SUPER_ADMIN", "USER.CREATE.SUPER_ADMIN"),
    ("USER.CREATE.ADMIN", "USER.CREATE.ADMIN"),
]
