version: "3.9"

services:
  arp_db:
    image: 'postgres:16'
    container_name: 'arp_db'
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - arp_db_net
    environment:
      - POSTGRES_USER=arp
      - POSTGRES_PASSWORD=@RP
      - POSTGRES_DB=arp

  arp_api:
    container_name: 'arp_api'
    image: arp_api
    ports:
      - 8000:8000
    build:
      context: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/arp_api
      - media:/media
      - static:/static
    networks:
      - arp_api_net
      - arp_db_net
    command: sh docker-entrypoint.sh
    depends_on:
      - arp_db

networks:
  arp_api_net:
    name: arp_api_net
    driver: bridge
  arp_db_net:
      name: arp_db_net
      driver: bridge

volumes:
  media:
  static:
