version: "3.9"

services:
  arp_api:
    container_name: 'arp_api'
    image: arp_api
    ports:
      - 8000:8000
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/arp_api
      - media:/media
    networks:
      - arp_net
    command: sh docker-entrypoint.sh
    depends_on:
      - arp_db

  arp_db:
    image: 'postgres:16'
    container_name: 'arp_db'
    restart: unless-stopped
    ports:
      - 5434:5434
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - arp_net
    environment:
      - POSTGRES_USER=arp
      - POSTGRES_PASSWORD=@RP
      - POSTGRES_DB=arp

networks:
  arp_net:
    name: arp_net
    driver: bridge
